[2025-09-20T17:57:20.402+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-09-20T17:57:20.506+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: bronze_full_load_spaceparts.extract_load_dim_Invoice_DocType scheduled__2024-01-01T00:00:00+00:00 [queued]>
[2025-09-20T17:57:20.540+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: bronze_full_load_spaceparts.extract_load_dim_Invoice_DocType scheduled__2024-01-01T00:00:00+00:00 [queued]>
[2025-09-20T17:57:20.540+0000] {taskinstance.py:2867} INFO - Starting attempt 3 of 3
[2025-09-20T17:57:20.601+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): extract_load_dim_Invoice_DocType> on 2024-01-01 00:00:00+00:00
[2025-09-20T17:57:20.622+0000] {standard_task_runner.py:72} INFO - Started process 235 to run task
[2025-09-20T17:57:20.629+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'bronze_full_load_spaceparts', 'extract_load_dim_Invoice_DocType', 'scheduled__2024-01-01T00:00:00+00:00', '--job-id', '48', '--raw', '--subdir', 'DAGS_FOLDER/01_Bronce.py', '--cfg-path', '/tmp/tmpngfj4qp6']
[2025-09-20T17:57:20.636+0000] {standard_task_runner.py:105} INFO - Job 48: Subtask extract_load_dim_Invoice_DocType
[2025-09-20T17:57:21.314+0000] {task_command.py:467} INFO - Running <TaskInstance: bronze_full_load_spaceparts.extract_load_dim_Invoice_DocType scheduled__2024-01-01T00:00:00+00:00 [running]> on host 2ddf28c2d814
[2025-09-20T17:57:21.532+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='data-team' AIRFLOW_CTX_DAG_ID='bronze_full_load_spaceparts' AIRFLOW_CTX_TASK_ID='extract_load_dim_Invoice_DocType' AIRFLOW_CTX_EXECUTION_DATE='2024-01-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-01T00:00:00+00:00'
[2025-09-20T17:57:21.534+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-09-20T17:57:21.553+0000] {01_Bronce.py:327} INFO - Starting extraction for table: dim.Invoice-DocType
[2025-09-20T17:57:24.636+0000] {01_Bronce.py:339} INFO - Table dim.Invoice-DocType has 5 rows
[2025-09-20T17:57:24.637+0000] {01_Bronce.py:353} INFO - Extracting data from dim.Invoice-DocType
[2025-09-20T17:57:30.790+0000] {01_Bronce.py:370} INFO - Loading 5 rows to bronze_dim_invoice_doctype
[2025-09-20T17:57:30.803+0000] {01_Bronce.py:303} ERROR - Error loading data to bronze_dim_invoice_doctype: (psycopg2.errors.SyntaxError) syntax error at or near "%"
LINE 4:                 WHERE table_name = %s
                                           ^

[SQL: 
            SELECT EXISTS (
                SELECT FROM information_schema.tables 
                WHERE table_name = %%s
            )
        ]
(Background on this error at: https://sqlalche.me/e/14/f405)
[2025-09-20T17:57:30.804+0000] {01_Bronce.py:388} ERROR - Error processing table dim.Invoice-DocType: (psycopg2.errors.SyntaxError) syntax error at or near "%"
LINE 4:                 WHERE table_name = %s
                                           ^

[SQL: 
            SELECT EXISTS (
                SELECT FROM information_schema.tables 
                WHERE table_name = %%s
            )
        ]
(Background on this error at: https://sqlalche.me/e/14/f405)
[2025-09-20T17:57:30.821+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1910, in _execute_context
    self.dialect.do_execute(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.SyntaxError: syntax error at or near "%"
LINE 4:                 WHERE table_name = %s
                                           ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/opt/airflow/dags/01_Bronce.py", line 371, in extract_and_load_table
    records_loaded = loader.load_data(df, bronze_table_name, if_exists='replace')
  File "/opt/airflow/dags/01_Bronce.py", line 288, in load_data
    self.create_table_if_not_exists(table_name, df_clean)
  File "/opt/airflow/dags/01_Bronce.py", line 230, in create_table_if_not_exists
    result = conn.execute(text(table_exists_query), (table_name,))
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1385, in execute
    return meth(self, multiparams, params, _EMPTY_EXECUTION_OPTS)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/sql/elements.py", line 334, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1577, in _execute_clauseelement
    ret = self._execute_context(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1953, in _execute_context
    self._handle_dbapi_exception(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 2134, in _handle_dbapi_exception
    util.raise_(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1910, in _execute_context
    self.dialect.do_execute(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.ProgrammingError: (psycopg2.errors.SyntaxError) syntax error at or near "%"
LINE 4:                 WHERE table_name = %s
                                           ^

[SQL: 
            SELECT EXISTS (
                SELECT FROM information_schema.tables 
                WHERE table_name = %%s
            )
        ]
(Background on this error at: https://sqlalche.me/e/14/f405)
[2025-09-20T17:57:30.833+0000] {taskinstance.py:1226} INFO - Marking task as FAILED. dag_id=bronze_full_load_spaceparts, task_id=extract_load_dim_Invoice_DocType, run_id=scheduled__2024-01-01T00:00:00+00:00, execution_date=20240101T000000, start_date=20250920T175720, end_date=20250920T175730
[2025-09-20T17:57:30.873+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-09-20T17:57:30.874+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 48 for task extract_load_dim_Invoice_DocType ((psycopg2.errors.SyntaxError) syntax error at or near "%"
LINE 4:                 WHERE table_name = %s
                                           ^

[SQL: 
            SELECT EXISTS (
                SELECT FROM information_schema.tables 
                WHERE table_name = %%s
            )
        ]
(Background on this error at: https://sqlalche.me/e/14/f405); 235)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1910, in _execute_context
    self.dialect.do_execute(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.SyntaxError: syntax error at or near "%"
LINE 4:                 WHERE table_name = %s
                                           ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/opt/airflow/dags/01_Bronce.py", line 371, in extract_and_load_table
    records_loaded = loader.load_data(df, bronze_table_name, if_exists='replace')
  File "/opt/airflow/dags/01_Bronce.py", line 288, in load_data
    self.create_table_if_not_exists(table_name, df_clean)
  File "/opt/airflow/dags/01_Bronce.py", line 230, in create_table_if_not_exists
    result = conn.execute(text(table_exists_query), (table_name,))
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1385, in execute
    return meth(self, multiparams, params, _EMPTY_EXECUTION_OPTS)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/sql/elements.py", line 334, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1577, in _execute_clauseelement
    ret = self._execute_context(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1953, in _execute_context
    self._handle_dbapi_exception(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 2134, in _handle_dbapi_exception
    util.raise_(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1910, in _execute_context
    self.dialect.do_execute(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.ProgrammingError: (psycopg2.errors.SyntaxError) syntax error at or near "%"
LINE 4:                 WHERE table_name = %s
                                           ^

[SQL: 
            SELECT EXISTS (
                SELECT FROM information_schema.tables 
                WHERE table_name = %%s
            )
        ]
(Background on this error at: https://sqlalche.me/e/14/f405)
[2025-09-20T17:57:30.929+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-09-20T17:57:30.987+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-09-20T17:57:30.989+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-09-20T18:16:03.126+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-09-20T18:16:03.145+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: bronze_full_load_spaceparts.extract_load_dim_Invoice_DocType scheduled__2024-01-01T00:00:00+00:00 [queued]>
[2025-09-20T18:16:03.152+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: bronze_full_load_spaceparts.extract_load_dim_Invoice_DocType scheduled__2024-01-01T00:00:00+00:00 [queued]>
[2025-09-20T18:16:03.152+0000] {taskinstance.py:2867} INFO - Starting attempt 3 of 3
[2025-09-20T18:16:03.164+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): extract_load_dim_Invoice_DocType> on 2024-01-01 00:00:00+00:00
[2025-09-20T18:16:03.168+0000] {standard_task_runner.py:72} INFO - Started process 136 to run task
[2025-09-20T18:16:03.175+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'bronze_full_load_spaceparts', 'extract_load_dim_Invoice_DocType', 'scheduled__2024-01-01T00:00:00+00:00', '--job-id', '88', '--raw', '--subdir', 'DAGS_FOLDER/01_Bronce.py', '--cfg-path', '/tmp/tmph9lrfba1']
[2025-09-20T18:16:03.177+0000] {standard_task_runner.py:105} INFO - Job 88: Subtask extract_load_dim_Invoice_DocType
[2025-09-20T18:16:03.356+0000] {task_command.py:467} INFO - Running <TaskInstance: bronze_full_load_spaceparts.extract_load_dim_Invoice_DocType scheduled__2024-01-01T00:00:00+00:00 [running]> on host 93ad4bfc4402
[2025-09-20T18:16:03.416+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='data-team' AIRFLOW_CTX_DAG_ID='bronze_full_load_spaceparts' AIRFLOW_CTX_TASK_ID='extract_load_dim_Invoice_DocType' AIRFLOW_CTX_EXECUTION_DATE='2024-01-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-01T00:00:00+00:00'
[2025-09-20T18:16:03.417+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-09-20T18:16:03.424+0000] {01_Bronce.py:272} INFO - Starting extraction for table: dim.Invoice-DocType
[2025-09-20T18:16:06.420+0000] {01_Bronce.py:284} INFO - Table dim.Invoice-DocType has 5 rows
[2025-09-20T18:16:06.421+0000] {01_Bronce.py:298} INFO - Extracting data from dim.Invoice-DocType
[2025-09-20T18:16:08.882+0000] {01_Bronce.py:315} INFO - Loading 5 rows to bronze_dim_invoice_doctype
[2025-09-20T18:16:08.917+0000] {01_Bronce.py:244} INFO - Loaded 5 rows to bronze_dim_invoice_doctype
[2025-09-20T18:16:08.918+0000] {01_Bronce.py:326} INFO - Successfully loaded 5 records to bronze_dim_invoice_doctype
[2025-09-20T18:16:08.932+0000] {python.py:240} INFO - Done. Returned value was: {'source_table': 'dim.Invoice-DocType', 'bronze_table': 'bronze_dim_invoice_doctype', 'record_count': 5, 'status': 'success', 'extraction_time': '2025-09-20T18:16:08.918210'}
[2025-09-20T18:16:08.955+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-09-20T18:16:08.956+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=bronze_full_load_spaceparts, task_id=extract_load_dim_Invoice_DocType, run_id=scheduled__2024-01-01T00:00:00+00:00, execution_date=20240101T000000, start_date=20250920T181603, end_date=20250920T181608
[2025-09-20T18:16:09.006+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-09-20T18:16:09.029+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-09-20T18:16:09.030+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
