[2025-09-20T17:57:20.294+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-09-20T17:57:20.360+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: bronze_full_load_spaceparts.extract_load_dim_Order_DocType scheduled__2024-01-01T00:00:00+00:00 [queued]>
[2025-09-20T17:57:20.391+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: bronze_full_load_spaceparts.extract_load_dim_Order_DocType scheduled__2024-01-01T00:00:00+00:00 [queued]>
[2025-09-20T17:57:20.392+0000] {taskinstance.py:2867} INFO - Starting attempt 3 of 3
[2025-09-20T17:57:20.428+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): extract_load_dim_Order_DocType> on 2024-01-01 00:00:00+00:00
[2025-09-20T17:57:20.441+0000] {standard_task_runner.py:72} INFO - Started process 233 to run task
[2025-09-20T17:57:20.450+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'bronze_full_load_spaceparts', 'extract_load_dim_Order_DocType', 'scheduled__2024-01-01T00:00:00+00:00', '--job-id', '47', '--raw', '--subdir', 'DAGS_FOLDER/01_Bronce.py', '--cfg-path', '/tmp/tmpecit1lio']
[2025-09-20T17:57:20.457+0000] {standard_task_runner.py:105} INFO - Job 47: Subtask extract_load_dim_Order_DocType
[2025-09-20T17:57:21.136+0000] {task_command.py:467} INFO - Running <TaskInstance: bronze_full_load_spaceparts.extract_load_dim_Order_DocType scheduled__2024-01-01T00:00:00+00:00 [running]> on host 2ddf28c2d814
[2025-09-20T17:57:21.390+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='data-team' AIRFLOW_CTX_DAG_ID='bronze_full_load_spaceparts' AIRFLOW_CTX_TASK_ID='extract_load_dim_Order_DocType' AIRFLOW_CTX_EXECUTION_DATE='2024-01-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-01T00:00:00+00:00'
[2025-09-20T17:57:21.393+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-09-20T17:57:21.421+0000] {01_Bronce.py:327} INFO - Starting extraction for table: dim.Order-DocType
[2025-09-20T17:57:24.477+0000] {01_Bronce.py:339} INFO - Table dim.Order-DocType has 4 rows
[2025-09-20T17:57:24.478+0000] {01_Bronce.py:353} INFO - Extracting data from dim.Order-DocType
[2025-09-20T17:57:30.584+0000] {01_Bronce.py:370} INFO - Loading 4 rows to bronze_dim_order_doctype
[2025-09-20T17:57:30.599+0000] {01_Bronce.py:303} ERROR - Error loading data to bronze_dim_order_doctype: (psycopg2.errors.SyntaxError) syntax error at or near "%"
LINE 4:                 WHERE table_name = %s
                                           ^

[SQL: 
            SELECT EXISTS (
                SELECT FROM information_schema.tables 
                WHERE table_name = %%s
            )
        ]
(Background on this error at: https://sqlalche.me/e/14/f405)
[2025-09-20T17:57:30.600+0000] {01_Bronce.py:388} ERROR - Error processing table dim.Order-DocType: (psycopg2.errors.SyntaxError) syntax error at or near "%"
LINE 4:                 WHERE table_name = %s
                                           ^

[SQL: 
            SELECT EXISTS (
                SELECT FROM information_schema.tables 
                WHERE table_name = %%s
            )
        ]
(Background on this error at: https://sqlalche.me/e/14/f405)
[2025-09-20T17:57:30.637+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1910, in _execute_context
    self.dialect.do_execute(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.SyntaxError: syntax error at or near "%"
LINE 4:                 WHERE table_name = %s
                                           ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/opt/airflow/dags/01_Bronce.py", line 371, in extract_and_load_table
    records_loaded = loader.load_data(df, bronze_table_name, if_exists='replace')
  File "/opt/airflow/dags/01_Bronce.py", line 288, in load_data
    self.create_table_if_not_exists(table_name, df_clean)
  File "/opt/airflow/dags/01_Bronce.py", line 230, in create_table_if_not_exists
    result = conn.execute(text(table_exists_query), (table_name,))
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1385, in execute
    return meth(self, multiparams, params, _EMPTY_EXECUTION_OPTS)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/sql/elements.py", line 334, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1577, in _execute_clauseelement
    ret = self._execute_context(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1953, in _execute_context
    self._handle_dbapi_exception(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 2134, in _handle_dbapi_exception
    util.raise_(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1910, in _execute_context
    self.dialect.do_execute(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.ProgrammingError: (psycopg2.errors.SyntaxError) syntax error at or near "%"
LINE 4:                 WHERE table_name = %s
                                           ^

[SQL: 
            SELECT EXISTS (
                SELECT FROM information_schema.tables 
                WHERE table_name = %%s
            )
        ]
(Background on this error at: https://sqlalche.me/e/14/f405)
[2025-09-20T17:57:30.652+0000] {taskinstance.py:1226} INFO - Marking task as FAILED. dag_id=bronze_full_load_spaceparts, task_id=extract_load_dim_Order_DocType, run_id=scheduled__2024-01-01T00:00:00+00:00, execution_date=20240101T000000, start_date=20250920T175720, end_date=20250920T175730
[2025-09-20T17:57:30.681+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-09-20T17:57:30.682+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 47 for task extract_load_dim_Order_DocType ((psycopg2.errors.SyntaxError) syntax error at or near "%"
LINE 4:                 WHERE table_name = %s
                                           ^

[SQL: 
            SELECT EXISTS (
                SELECT FROM information_schema.tables 
                WHERE table_name = %%s
            )
        ]
(Background on this error at: https://sqlalche.me/e/14/f405); 233)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1910, in _execute_context
    self.dialect.do_execute(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.SyntaxError: syntax error at or near "%"
LINE 4:                 WHERE table_name = %s
                                           ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/opt/airflow/dags/01_Bronce.py", line 371, in extract_and_load_table
    records_loaded = loader.load_data(df, bronze_table_name, if_exists='replace')
  File "/opt/airflow/dags/01_Bronce.py", line 288, in load_data
    self.create_table_if_not_exists(table_name, df_clean)
  File "/opt/airflow/dags/01_Bronce.py", line 230, in create_table_if_not_exists
    result = conn.execute(text(table_exists_query), (table_name,))
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1385, in execute
    return meth(self, multiparams, params, _EMPTY_EXECUTION_OPTS)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/sql/elements.py", line 334, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1577, in _execute_clauseelement
    ret = self._execute_context(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1953, in _execute_context
    self._handle_dbapi_exception(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 2134, in _handle_dbapi_exception
    util.raise_(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1910, in _execute_context
    self.dialect.do_execute(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.ProgrammingError: (psycopg2.errors.SyntaxError) syntax error at or near "%"
LINE 4:                 WHERE table_name = %s
                                           ^

[SQL: 
            SELECT EXISTS (
                SELECT FROM information_schema.tables 
                WHERE table_name = %%s
            )
        ]
(Background on this error at: https://sqlalche.me/e/14/f405)
[2025-09-20T17:57:30.707+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-09-20T17:57:30.743+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-09-20T17:57:30.746+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-09-20T18:16:03.351+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-09-20T18:16:03.367+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: bronze_full_load_spaceparts.extract_load_dim_Order_DocType scheduled__2024-01-01T00:00:00+00:00 [queued]>
[2025-09-20T18:16:03.374+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: bronze_full_load_spaceparts.extract_load_dim_Order_DocType scheduled__2024-01-01T00:00:00+00:00 [queued]>
[2025-09-20T18:16:03.374+0000] {taskinstance.py:2867} INFO - Starting attempt 3 of 3
[2025-09-20T18:16:03.384+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): extract_load_dim_Order_DocType> on 2024-01-01 00:00:00+00:00
[2025-09-20T18:16:03.387+0000] {standard_task_runner.py:72} INFO - Started process 143 to run task
[2025-09-20T18:16:03.390+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'bronze_full_load_spaceparts', 'extract_load_dim_Order_DocType', 'scheduled__2024-01-01T00:00:00+00:00', '--job-id', '92', '--raw', '--subdir', 'DAGS_FOLDER/01_Bronce.py', '--cfg-path', '/tmp/tmp7u_yyeq8']
[2025-09-20T18:16:03.393+0000] {standard_task_runner.py:105} INFO - Job 92: Subtask extract_load_dim_Order_DocType
[2025-09-20T18:16:03.565+0000] {task_command.py:467} INFO - Running <TaskInstance: bronze_full_load_spaceparts.extract_load_dim_Order_DocType scheduled__2024-01-01T00:00:00+00:00 [running]> on host 93ad4bfc4402
[2025-09-20T18:16:03.608+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='data-team' AIRFLOW_CTX_DAG_ID='bronze_full_load_spaceparts' AIRFLOW_CTX_TASK_ID='extract_load_dim_Order_DocType' AIRFLOW_CTX_EXECUTION_DATE='2024-01-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-01T00:00:00+00:00'
[2025-09-20T18:16:03.609+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-09-20T18:16:03.616+0000] {01_Bronce.py:272} INFO - Starting extraction for table: dim.Order-DocType
[2025-09-20T18:16:06.649+0000] {01_Bronce.py:284} INFO - Table dim.Order-DocType has 4 rows
[2025-09-20T18:16:06.650+0000] {01_Bronce.py:298} INFO - Extracting data from dim.Order-DocType
[2025-09-20T18:16:08.995+0000] {01_Bronce.py:315} INFO - Loading 4 rows to bronze_dim_order_doctype
[2025-09-20T18:16:09.015+0000] {01_Bronce.py:244} INFO - Loaded 4 rows to bronze_dim_order_doctype
[2025-09-20T18:16:09.016+0000] {01_Bronce.py:326} INFO - Successfully loaded 4 records to bronze_dim_order_doctype
[2025-09-20T18:16:09.026+0000] {python.py:240} INFO - Done. Returned value was: {'source_table': 'dim.Order-DocType', 'bronze_table': 'bronze_dim_order_doctype', 'record_count': 4, 'status': 'success', 'extraction_time': '2025-09-20T18:16:09.016107'}
[2025-09-20T18:16:09.040+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-09-20T18:16:09.041+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=bronze_full_load_spaceparts, task_id=extract_load_dim_Order_DocType, run_id=scheduled__2024-01-01T00:00:00+00:00, execution_date=20240101T000000, start_date=20250920T181603, end_date=20250920T181609
[2025-09-20T18:16:09.099+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-09-20T18:16:09.161+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-09-20T18:16:09.165+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
