[2025-09-20T17:57:20.467+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-09-20T17:57:20.522+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: bronze_full_load_spaceparts.extract_load_dim_Employees scheduled__2024-01-01T00:00:00+00:00 [queued]>
[2025-09-20T17:57:20.554+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: bronze_full_load_spaceparts.extract_load_dim_Employees scheduled__2024-01-01T00:00:00+00:00 [queued]>
[2025-09-20T17:57:20.554+0000] {taskinstance.py:2867} INFO - Starting attempt 3 of 3
[2025-09-20T17:57:20.612+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): extract_load_dim_Employees> on 2024-01-01 00:00:00+00:00
[2025-09-20T17:57:20.633+0000] {standard_task_runner.py:72} INFO - Started process 237 to run task
[2025-09-20T17:57:20.681+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'bronze_full_load_spaceparts', 'extract_load_dim_Employees', 'scheduled__2024-01-01T00:00:00+00:00', '--job-id', '50', '--raw', '--subdir', 'DAGS_FOLDER/01_Bronce.py', '--cfg-path', '/tmp/tmpfez6ei2k']
[2025-09-20T17:57:20.709+0000] {standard_task_runner.py:105} INFO - Job 50: Subtask extract_load_dim_Employees
[2025-09-20T17:57:21.347+0000] {task_command.py:467} INFO - Running <TaskInstance: bronze_full_load_spaceparts.extract_load_dim_Employees scheduled__2024-01-01T00:00:00+00:00 [running]> on host 2ddf28c2d814
[2025-09-20T17:57:21.595+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='data-team' AIRFLOW_CTX_DAG_ID='bronze_full_load_spaceparts' AIRFLOW_CTX_TASK_ID='extract_load_dim_Employees' AIRFLOW_CTX_EXECUTION_DATE='2024-01-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-01T00:00:00+00:00'
[2025-09-20T17:57:21.596+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-09-20T17:57:21.617+0000] {01_Bronce.py:327} INFO - Starting extraction for table: dim.Employees
[2025-09-20T17:57:24.737+0000] {01_Bronce.py:339} INFO - Table dim.Employees has 893 rows
[2025-09-20T17:57:24.738+0000] {01_Bronce.py:353} INFO - Extracting data from dim.Employees
[2025-09-20T17:57:31.387+0000] {01_Bronce.py:370} INFO - Loading 893 rows to bronze_dim_employees
[2025-09-20T17:57:31.406+0000] {01_Bronce.py:303} ERROR - Error loading data to bronze_dim_employees: (psycopg2.errors.SyntaxError) syntax error at or near "%"
LINE 4:                 WHERE table_name = %s
                                           ^

[SQL: 
            SELECT EXISTS (
                SELECT FROM information_schema.tables 
                WHERE table_name = %%s
            )
        ]
(Background on this error at: https://sqlalche.me/e/14/f405)
[2025-09-20T17:57:31.407+0000] {01_Bronce.py:388} ERROR - Error processing table dim.Employees: (psycopg2.errors.SyntaxError) syntax error at or near "%"
LINE 4:                 WHERE table_name = %s
                                           ^

[SQL: 
            SELECT EXISTS (
                SELECT FROM information_schema.tables 
                WHERE table_name = %%s
            )
        ]
(Background on this error at: https://sqlalche.me/e/14/f405)
[2025-09-20T17:57:31.426+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1910, in _execute_context
    self.dialect.do_execute(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.SyntaxError: syntax error at or near "%"
LINE 4:                 WHERE table_name = %s
                                           ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/opt/airflow/dags/01_Bronce.py", line 371, in extract_and_load_table
    records_loaded = loader.load_data(df, bronze_table_name, if_exists='replace')
  File "/opt/airflow/dags/01_Bronce.py", line 288, in load_data
    self.create_table_if_not_exists(table_name, df_clean)
  File "/opt/airflow/dags/01_Bronce.py", line 230, in create_table_if_not_exists
    result = conn.execute(text(table_exists_query), (table_name,))
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1385, in execute
    return meth(self, multiparams, params, _EMPTY_EXECUTION_OPTS)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/sql/elements.py", line 334, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1577, in _execute_clauseelement
    ret = self._execute_context(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1953, in _execute_context
    self._handle_dbapi_exception(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 2134, in _handle_dbapi_exception
    util.raise_(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1910, in _execute_context
    self.dialect.do_execute(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.ProgrammingError: (psycopg2.errors.SyntaxError) syntax error at or near "%"
LINE 4:                 WHERE table_name = %s
                                           ^

[SQL: 
            SELECT EXISTS (
                SELECT FROM information_schema.tables 
                WHERE table_name = %%s
            )
        ]
(Background on this error at: https://sqlalche.me/e/14/f405)
[2025-09-20T17:57:31.453+0000] {taskinstance.py:1226} INFO - Marking task as FAILED. dag_id=bronze_full_load_spaceparts, task_id=extract_load_dim_Employees, run_id=scheduled__2024-01-01T00:00:00+00:00, execution_date=20240101T000000, start_date=20250920T175720, end_date=20250920T175731
[2025-09-20T17:57:31.504+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-09-20T17:57:31.506+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 50 for task extract_load_dim_Employees ((psycopg2.errors.SyntaxError) syntax error at or near "%"
LINE 4:                 WHERE table_name = %s
                                           ^

[SQL: 
            SELECT EXISTS (
                SELECT FROM information_schema.tables 
                WHERE table_name = %%s
            )
        ]
(Background on this error at: https://sqlalche.me/e/14/f405); 237)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1910, in _execute_context
    self.dialect.do_execute(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.SyntaxError: syntax error at or near "%"
LINE 4:                 WHERE table_name = %s
                                           ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/opt/airflow/dags/01_Bronce.py", line 371, in extract_and_load_table
    records_loaded = loader.load_data(df, bronze_table_name, if_exists='replace')
  File "/opt/airflow/dags/01_Bronce.py", line 288, in load_data
    self.create_table_if_not_exists(table_name, df_clean)
  File "/opt/airflow/dags/01_Bronce.py", line 230, in create_table_if_not_exists
    result = conn.execute(text(table_exists_query), (table_name,))
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1385, in execute
    return meth(self, multiparams, params, _EMPTY_EXECUTION_OPTS)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/sql/elements.py", line 334, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1577, in _execute_clauseelement
    ret = self._execute_context(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1953, in _execute_context
    self._handle_dbapi_exception(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 2134, in _handle_dbapi_exception
    util.raise_(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1910, in _execute_context
    self.dialect.do_execute(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.ProgrammingError: (psycopg2.errors.SyntaxError) syntax error at or near "%"
LINE 4:                 WHERE table_name = %s
                                           ^

[SQL: 
            SELECT EXISTS (
                SELECT FROM information_schema.tables 
                WHERE table_name = %%s
            )
        ]
(Background on this error at: https://sqlalche.me/e/14/f405)
[2025-09-20T17:57:31.550+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-09-20T17:57:31.632+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-09-20T17:57:31.636+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-09-20T18:16:04.841+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-09-20T18:16:04.853+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: bronze_full_load_spaceparts.extract_load_dim_Employees scheduled__2024-01-01T00:00:00+00:00 [queued]>
[2025-09-20T18:16:04.859+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: bronze_full_load_spaceparts.extract_load_dim_Employees scheduled__2024-01-01T00:00:00+00:00 [queued]>
[2025-09-20T18:16:04.860+0000] {taskinstance.py:2867} INFO - Starting attempt 3 of 3
[2025-09-20T18:16:04.869+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): extract_load_dim_Employees> on 2024-01-01 00:00:00+00:00
[2025-09-20T18:16:04.872+0000] {standard_task_runner.py:72} INFO - Started process 154 to run task
[2025-09-20T18:16:04.874+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'bronze_full_load_spaceparts', 'extract_load_dim_Employees', 'scheduled__2024-01-01T00:00:00+00:00', '--job-id', '94', '--raw', '--subdir', 'DAGS_FOLDER/01_Bronce.py', '--cfg-path', '/tmp/tmpn8g91erv']
[2025-09-20T18:16:04.877+0000] {standard_task_runner.py:105} INFO - Job 94: Subtask extract_load_dim_Employees
[2025-09-20T18:16:05.076+0000] {task_command.py:467} INFO - Running <TaskInstance: bronze_full_load_spaceparts.extract_load_dim_Employees scheduled__2024-01-01T00:00:00+00:00 [running]> on host 93ad4bfc4402
[2025-09-20T18:16:05.127+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='data-team' AIRFLOW_CTX_DAG_ID='bronze_full_load_spaceparts' AIRFLOW_CTX_TASK_ID='extract_load_dim_Employees' AIRFLOW_CTX_EXECUTION_DATE='2024-01-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-01T00:00:00+00:00'
[2025-09-20T18:16:05.128+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-09-20T18:16:05.134+0000] {01_Bronce.py:272} INFO - Starting extraction for table: dim.Employees
[2025-09-20T18:16:08.110+0000] {01_Bronce.py:284} INFO - Table dim.Employees has 893 rows
[2025-09-20T18:16:08.111+0000] {01_Bronce.py:298} INFO - Extracting data from dim.Employees
[2025-09-20T18:16:11.306+0000] {01_Bronce.py:315} INFO - Loading 893 rows to bronze_dim_employees
[2025-09-20T18:16:11.385+0000] {01_Bronce.py:244} INFO - Loaded 893 rows to bronze_dim_employees
[2025-09-20T18:16:11.386+0000] {01_Bronce.py:326} INFO - Successfully loaded 893 records to bronze_dim_employees
[2025-09-20T18:16:11.395+0000] {python.py:240} INFO - Done. Returned value was: {'source_table': 'dim.Employees', 'bronze_table': 'bronze_dim_employees', 'record_count': 893, 'status': 'success', 'extraction_time': '2025-09-20T18:16:11.386245'}
[2025-09-20T18:16:11.408+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-09-20T18:16:11.408+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=bronze_full_load_spaceparts, task_id=extract_load_dim_Employees, run_id=scheduled__2024-01-01T00:00:00+00:00, execution_date=20240101T000000, start_date=20250920T181604, end_date=20250920T181611
[2025-09-20T18:16:11.441+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-09-20T18:16:11.461+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-09-20T18:16:11.463+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
