[2025-09-20T17:37:51.433+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-09-20T17:37:51.599+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: bronze_full_load_spaceparts.get_table_list scheduled__2024-01-01T00:00:00+00:00 [queued]>
[2025-09-20T17:37:51.607+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: bronze_full_load_spaceparts.get_table_list scheduled__2024-01-01T00:00:00+00:00 [queued]>
[2025-09-20T17:37:51.607+0000] {taskinstance.py:2867} INFO - Starting attempt 2 of 3
[2025-09-20T17:37:51.619+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): get_table_list> on 2024-01-01 00:00:00+00:00
[2025-09-20T17:37:51.622+0000] {standard_task_runner.py:72} INFO - Started process 91 to run task
[2025-09-20T17:37:51.627+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'bronze_full_load_spaceparts', 'get_table_list', 'scheduled__2024-01-01T00:00:00+00:00', '--job-id', '9', '--raw', '--subdir', 'DAGS_FOLDER/01_Bronce.py', '--cfg-path', '/tmp/tmpf3b24bmd']
[2025-09-20T17:37:51.630+0000] {standard_task_runner.py:105} INFO - Job 9: Subtask get_table_list
[2025-09-20T17:37:51.679+0000] {task_command.py:467} INFO - Running <TaskInstance: bronze_full_load_spaceparts.get_table_list scheduled__2024-01-01T00:00:00+00:00 [running]> on host fa866e4b5959
[2025-09-20T17:37:51.752+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='data-team' AIRFLOW_CTX_DAG_ID='bronze_full_load_spaceparts' AIRFLOW_CTX_TASK_ID='get_table_list' AIRFLOW_CTX_EXECUTION_DATE='2024-01-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-01T00:00:00+00:00'
[2025-09-20T17:37:51.753+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-09-20T17:37:55.861+0000] {01_Bronce.py:316} ERROR - Error getting table list: ('42000', '[42000] [Microsoft][ODBC Driver 18 for SQL Server][SQL Server]Cannot open database "spaceparts" requested by the login. The login failed. (4060) (SQLDriverConnect)')
[2025-09-20T17:37:55.863+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/opt/airflow/dags/01_Bronce.py", line 309, in get_table_list
    tables = profiler.list_tables()
  File "/opt/airflow/dags/01_Bronce.py", line 157, in list_tables
    with self.source_manager.get_connection() as conn:
  File "/opt/airflow/dags/01_Bronce.py", line 56, in get_connection
    return pyodbc.connect(self.get_connection_string())
pyodbc.ProgrammingError: ('42000', '[42000] [Microsoft][ODBC Driver 18 for SQL Server][SQL Server]Cannot open database "spaceparts" requested by the login. The login failed. (4060) (SQLDriverConnect)')
[2025-09-20T17:37:55.897+0000] {taskinstance.py:1226} INFO - Marking task as UP_FOR_RETRY. dag_id=bronze_full_load_spaceparts, task_id=get_table_list, run_id=scheduled__2024-01-01T00:00:00+00:00, execution_date=20240101T000000, start_date=20250920T173751, end_date=20250920T173755
[2025-09-20T17:37:55.968+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-09-20T17:37:55.969+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 9 for task get_table_list (('42000', '[42000] [Microsoft][ODBC Driver 18 for SQL Server][SQL Server]Cannot open database "spaceparts" requested by the login. The login failed. (4060) (SQLDriverConnect)'); 91)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/opt/airflow/dags/01_Bronce.py", line 309, in get_table_list
    tables = profiler.list_tables()
  File "/opt/airflow/dags/01_Bronce.py", line 157, in list_tables
    with self.source_manager.get_connection() as conn:
  File "/opt/airflow/dags/01_Bronce.py", line 56, in get_connection
    return pyodbc.connect(self.get_connection_string())
pyodbc.ProgrammingError: ('42000', '[42000] [Microsoft][ODBC Driver 18 for SQL Server][SQL Server]Cannot open database "spaceparts" requested by the login. The login failed. (4060) (SQLDriverConnect)')
[2025-09-20T17:37:56.017+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-09-20T17:37:56.053+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-09-20T17:37:56.057+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
