[2025-09-20T17:57:55.268+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-09-20T17:57:55.313+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: bronze_full_load_spaceparts.extract_load_dim_Products scheduled__2024-01-01T00:00:00+00:00 [queued]>
[2025-09-20T17:57:55.341+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: bronze_full_load_spaceparts.extract_load_dim_Products scheduled__2024-01-01T00:00:00+00:00 [queued]>
[2025-09-20T17:57:55.341+0000] {taskinstance.py:2867} INFO - Starting attempt 3 of 3
[2025-09-20T17:57:55.385+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): extract_load_dim_Products> on 2024-01-01 00:00:00+00:00
[2025-09-20T17:57:55.396+0000] {standard_task_runner.py:72} INFO - Started process 258 to run task
[2025-09-20T17:57:55.413+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'bronze_full_load_spaceparts', 'extract_load_dim_Products', 'scheduled__2024-01-01T00:00:00+00:00', '--job-id', '54', '--raw', '--subdir', 'DAGS_FOLDER/01_Bronce.py', '--cfg-path', '/tmp/tmpezhjf8hy']
[2025-09-20T17:57:55.421+0000] {standard_task_runner.py:105} INFO - Job 54: Subtask extract_load_dim_Products
[2025-09-20T17:57:55.701+0000] {task_command.py:467} INFO - Running <TaskInstance: bronze_full_load_spaceparts.extract_load_dim_Products scheduled__2024-01-01T00:00:00+00:00 [running]> on host 2ddf28c2d814
[2025-09-20T17:57:55.802+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='data-team' AIRFLOW_CTX_DAG_ID='bronze_full_load_spaceparts' AIRFLOW_CTX_TASK_ID='extract_load_dim_Products' AIRFLOW_CTX_EXECUTION_DATE='2024-01-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-01T00:00:00+00:00'
[2025-09-20T17:57:55.803+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-09-20T17:57:55.816+0000] {01_Bronce.py:327} INFO - Starting extraction for table: dim.Products
[2025-09-20T17:57:59.206+0000] {01_Bronce.py:339} INFO - Table dim.Products has 256,293 rows
[2025-09-20T17:57:59.207+0000] {01_Bronce.py:353} INFO - Extracting data from dim.Products
[2025-09-20T17:58:15.744+0000] {01_Bronce.py:370} INFO - Loading 256293 rows to bronze_dim_products
[2025-09-20T17:58:16.408+0000] {01_Bronce.py:303} ERROR - Error loading data to bronze_dim_products: (psycopg2.errors.SyntaxError) syntax error at or near "%"
LINE 4:                 WHERE table_name = %s
                                           ^

[SQL: 
            SELECT EXISTS (
                SELECT FROM information_schema.tables 
                WHERE table_name = %%s
            )
        ]
(Background on this error at: https://sqlalche.me/e/14/f405)
[2025-09-20T17:58:16.409+0000] {01_Bronce.py:388} ERROR - Error processing table dim.Products: (psycopg2.errors.SyntaxError) syntax error at or near "%"
LINE 4:                 WHERE table_name = %s
                                           ^

[SQL: 
            SELECT EXISTS (
                SELECT FROM information_schema.tables 
                WHERE table_name = %%s
            )
        ]
(Background on this error at: https://sqlalche.me/e/14/f405)
[2025-09-20T17:58:16.436+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1910, in _execute_context
    self.dialect.do_execute(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.SyntaxError: syntax error at or near "%"
LINE 4:                 WHERE table_name = %s
                                           ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/opt/airflow/dags/01_Bronce.py", line 371, in extract_and_load_table
    records_loaded = loader.load_data(df, bronze_table_name, if_exists='replace')
  File "/opt/airflow/dags/01_Bronce.py", line 288, in load_data
    self.create_table_if_not_exists(table_name, df_clean)
  File "/opt/airflow/dags/01_Bronce.py", line 230, in create_table_if_not_exists
    result = conn.execute(text(table_exists_query), (table_name,))
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1385, in execute
    return meth(self, multiparams, params, _EMPTY_EXECUTION_OPTS)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/sql/elements.py", line 334, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1577, in _execute_clauseelement
    ret = self._execute_context(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1953, in _execute_context
    self._handle_dbapi_exception(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 2134, in _handle_dbapi_exception
    util.raise_(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1910, in _execute_context
    self.dialect.do_execute(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.ProgrammingError: (psycopg2.errors.SyntaxError) syntax error at or near "%"
LINE 4:                 WHERE table_name = %s
                                           ^

[SQL: 
            SELECT EXISTS (
                SELECT FROM information_schema.tables 
                WHERE table_name = %%s
            )
        ]
(Background on this error at: https://sqlalche.me/e/14/f405)
[2025-09-20T17:58:16.455+0000] {taskinstance.py:1226} INFO - Marking task as FAILED. dag_id=bronze_full_load_spaceparts, task_id=extract_load_dim_Products, run_id=scheduled__2024-01-01T00:00:00+00:00, execution_date=20240101T000000, start_date=20250920T175755, end_date=20250920T175816
[2025-09-20T17:58:16.518+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-09-20T17:58:16.518+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 54 for task extract_load_dim_Products ((psycopg2.errors.SyntaxError) syntax error at or near "%"
LINE 4:                 WHERE table_name = %s
                                           ^

[SQL: 
            SELECT EXISTS (
                SELECT FROM information_schema.tables 
                WHERE table_name = %%s
            )
        ]
(Background on this error at: https://sqlalche.me/e/14/f405); 258)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1910, in _execute_context
    self.dialect.do_execute(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.SyntaxError: syntax error at or near "%"
LINE 4:                 WHERE table_name = %s
                                           ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/opt/airflow/dags/01_Bronce.py", line 371, in extract_and_load_table
    records_loaded = loader.load_data(df, bronze_table_name, if_exists='replace')
  File "/opt/airflow/dags/01_Bronce.py", line 288, in load_data
    self.create_table_if_not_exists(table_name, df_clean)
  File "/opt/airflow/dags/01_Bronce.py", line 230, in create_table_if_not_exists
    result = conn.execute(text(table_exists_query), (table_name,))
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1385, in execute
    return meth(self, multiparams, params, _EMPTY_EXECUTION_OPTS)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/sql/elements.py", line 334, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1577, in _execute_clauseelement
    ret = self._execute_context(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1953, in _execute_context
    self._handle_dbapi_exception(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 2134, in _handle_dbapi_exception
    util.raise_(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1910, in _execute_context
    self.dialect.do_execute(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.ProgrammingError: (psycopg2.errors.SyntaxError) syntax error at or near "%"
LINE 4:                 WHERE table_name = %s
                                           ^

[SQL: 
            SELECT EXISTS (
                SELECT FROM information_schema.tables 
                WHERE table_name = %%s
            )
        ]
(Background on this error at: https://sqlalche.me/e/14/f405)
[2025-09-20T17:58:16.573+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-09-20T17:58:16.668+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-09-20T17:58:16.672+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-09-20T18:16:14.284+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-09-20T18:16:14.311+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: bronze_full_load_spaceparts.extract_load_dim_Products scheduled__2024-01-01T00:00:00+00:00 [queued]>
[2025-09-20T18:16:14.326+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: bronze_full_load_spaceparts.extract_load_dim_Products scheduled__2024-01-01T00:00:00+00:00 [queued]>
[2025-09-20T18:16:14.328+0000] {taskinstance.py:2867} INFO - Starting attempt 3 of 3
[2025-09-20T18:16:14.340+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): extract_load_dim_Products> on 2024-01-01 00:00:00+00:00
[2025-09-20T18:16:14.343+0000] {standard_task_runner.py:72} INFO - Started process 166 to run task
[2025-09-20T18:16:14.347+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'bronze_full_load_spaceparts', 'extract_load_dim_Products', 'scheduled__2024-01-01T00:00:00+00:00', '--job-id', '98', '--raw', '--subdir', 'DAGS_FOLDER/01_Bronce.py', '--cfg-path', '/tmp/tmpdnex2c88']
[2025-09-20T18:16:14.349+0000] {standard_task_runner.py:105} INFO - Job 98: Subtask extract_load_dim_Products
[2025-09-20T18:16:14.565+0000] {task_command.py:467} INFO - Running <TaskInstance: bronze_full_load_spaceparts.extract_load_dim_Products scheduled__2024-01-01T00:00:00+00:00 [running]> on host 93ad4bfc4402
[2025-09-20T18:16:14.633+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='data-team' AIRFLOW_CTX_DAG_ID='bronze_full_load_spaceparts' AIRFLOW_CTX_TASK_ID='extract_load_dim_Products' AIRFLOW_CTX_EXECUTION_DATE='2024-01-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-01T00:00:00+00:00'
[2025-09-20T18:16:14.634+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-09-20T18:16:14.641+0000] {01_Bronce.py:272} INFO - Starting extraction for table: dim.Products
[2025-09-20T18:16:17.739+0000] {01_Bronce.py:284} INFO - Table dim.Products has 256,293 rows
[2025-09-20T18:16:17.739+0000] {01_Bronce.py:298} INFO - Extracting data from dim.Products
[2025-09-20T18:16:42.727+0000] {01_Bronce.py:315} INFO - Loading 256293 rows to bronze_dim_products
